import { ComplianceQuery } from './compliance-query-types';

// ═══════════════════════════════════════════════════════════════
// DORA QUERIES (14)
// ═══════════════════════════════════════════════════════════════

export const DORA_QUERIES: ComplianceQuery[] = [
  {
    queryId: 'DORA-17-INCIDENT-CLASSIFICATION',
    name: 'ICT Incident Classification',
    description: 'Verify that ICT incidents are properly classified',
    regulation: 'DORA',
    articles: ['Art.17'],
    category: 'INCIDENT_MANAGEMENT',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'incident', type: 'EVENT', filters: { event_type: 'INCIDENT.CREATED' } },
        { alias: 'classification', type: 'DECISION', filters: { decision_type: 'CLASSIFICATION' } },
        { alias: 'actor', type: 'ACTOR', filters: { role: { in: ['INCIDENT_MANAGER', 'SECURITY_ANALYST'] } } },
      ],
      requiredEdges: [
        { type: 'LEADS_TO', from: 'incident', to: 'classification' },
        { type: 'MADE_BY', from: 'classification', to: 'actor' },
      ],
    },
    proofCriteria: [
      {
        id: 'classification-exists',
        description: 'Incident was classified',
        type: 'EXISTS',
        params: { nodeAlias: 'classification' },
        weight: 50,
        mandatory: true,
      },
      {
        id: 'justified',
        description: 'Classification has justification',
        type: 'VALUE',
        params: { nodeAlias: 'classification', field: 'justification', operator: 'EXISTS' },
        weight: 30,
        mandatory: true,
      },
      {
        id: 'authorized-actor',
        description: 'Classification by authorized personnel',
        type: 'EXISTS',
        params: { nodeAlias: 'actor' },
        weight: 20,
        mandatory: false,
      },
    ],
  },
  {
    queryId: 'DORA-19-MAJOR-INCIDENT-REPORTING',
    name: 'Major Incident Reporting (4h/24h)',
    description: 'Verify that major incidents are reported within regulatory timeframes',
    regulation: 'DORA',
    articles: ['Art.19'],
    category: 'INCIDENT_MANAGEMENT',
    severity: 'CRITICAL',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'incident', type: 'EVENT', filters: { event_type: 'INCIDENT.CREATED', 'payload.isMajor': true } },
        { alias: 'clock4h', type: 'CLOCK', filters: { clock_type: 'DORA_4H' } },
        { alias: 'clock24h', type: 'CLOCK', filters: { clock_type: 'DORA_24H' }, optional: true },
        { alias: 'notification', type: 'EVENT', filters: { event_type: 'COMMUNICATION.SENT' }, optional: true },
      ],
      requiredEdges: [
        { type: 'TRIGGERS', from: 'incident', to: 'clock4h' },
      ],
    },
    proofCriteria: [
      {
        id: 'initial-notification',
        description: '4-hour initial notification deadline met',
        type: 'VALUE',
        params: { nodeAlias: 'clock4h', field: 'status', operator: 'IN', value: ['MET', 'STOPPED'] },
        weight: 50,
        mandatory: true,
      },
      {
        id: 'intermediate-report',
        description: '24-hour intermediate report deadline met',
        type: 'VALUE',
        params: { nodeAlias: 'clock24h', field: 'status', operator: 'IN', value: ['MET', 'STOPPED'] },
        weight: 30,
        mandatory: false,
      },
      {
        id: 'notification-sent',
        description: 'Notification was sent to authorities',
        type: 'EXISTS',
        params: { nodeAlias: 'notification' },
        weight: 20,
        mandatory: false,
      },
    ],
  },
  {
    queryId: 'DORA-5-ICT-GOVERNANCE',
    name: 'ICT Governance Framework',
    description: 'Verify ICT governance policies are in place and approved',
    regulation: 'DORA',
    articles: ['Art.5'],
    category: 'GOVERNANCE',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'policy', type: 'EVENT', filters: { event_type: 'GOVERNANCE.POLICY.CREATED' } },
        { alias: 'approval', type: 'DECISION', filters: { decision_type: 'APPROVAL' } },
        { alias: 'executive', type: 'ACTOR', filters: { authority_level: { in: ['EXECUTIVE', 'BOARD'] } } },
      ],
      requiredEdges: [
        { type: 'MADE_BY', from: 'approval', to: 'executive' },
      ],
    },
    proofCriteria: [
      {
        id: 'policy-exists',
        description: 'ICT governance policies exist',
        type: 'EXISTS',
        params: { nodeAlias: 'policy' },
        weight: 40,
        mandatory: true,
      },
      {
        id: 'management-approval',
        description: 'Approved by management body',
        type: 'EXISTS',
        params: { nodeAlias: 'approval' },
        weight: 40,
        mandatory: true,
      },
      {
        id: 'executive-oversight',
        description: 'Executive/Board level oversight',
        type: 'EXISTS',
        params: { nodeAlias: 'executive' },
        weight: 20,
        mandatory: false,
      },
    ],
  },
  {
    queryId: 'DORA-6-ICT-RISK-MANAGEMENT',
    name: 'ICT Risk Management Framework',
    description: 'Verify ICT risk management framework is operational',
    regulation: 'DORA',
    articles: ['Art.6'],
    category: 'RISK_MANAGEMENT',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'assessment', type: 'EVENT', filters: { event_type: 'RISK.ASSESSMENT.COMPLETED' } },
        { alias: 'control', type: 'CONTROL', filters: { control_type: 'MONITORING' } },
      ],
      requiredEdges: [],
      timeConstraints: [
        { field: 'assessment.occurred_at', within: '12_MONTHS' },
      ],
    },
    proofCriteria: [
      {
        id: 'risk-assessments',
        description: 'Risk assessments are conducted',
        type: 'COUNT',
        params: { nodeAlias: 'assessment', minCount: 1 },
        weight: 50,
        mandatory: true,
      },
      {
        id: 'monitoring-active',
        description: 'Continuous monitoring is active',
        type: 'VALUE',
        params: { nodeAlias: 'control', field: 'status', operator: 'EQUALS', value: 'ACTIVE' },
        weight: 50,
        mandatory: true,
      },
    ],
  },
  {
    queryId: 'DORA-7-ICT-SYSTEMS-INVENTORY',
    name: 'ICT Systems Inventory',
    description: 'Verify complete inventory of ICT systems and assets',
    regulation: 'DORA',
    articles: ['Art.7'],
    category: 'DOCUMENTATION',
    severity: 'MEDIUM',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'asset', type: 'EVENT', filters: { event_type: 'ASSET.REGISTERED' }, minCount: 1 },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'assets-registered',
        description: 'ICT assets are registered in inventory',
        type: 'COUNT',
        params: { nodeAlias: 'asset', minCount: 1 },
        weight: 100,
        mandatory: true,
      },
    ],
  },
  {
    queryId: 'DORA-8-ASSET-IDENTIFICATION',
    name: 'ICT Asset Identification',
    description: 'Verify ICT assets supporting critical functions are identified',
    regulation: 'DORA',
    articles: ['Art.8'],
    category: 'DOCUMENTATION',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'critical_asset', type: 'EVENT', filters: { event_type: 'ASSET.REGISTERED', 'payload.criticality': 'CRITICAL' } },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'critical-identified',
        description: 'Critical assets are identified',
        type: 'COUNT',
        params: { nodeAlias: 'critical_asset', minCount: 1 },
        weight: 100,
        mandatory: true,
      },
    ],
  },
  {
    queryId: 'DORA-9-DATA-PROTECTION',
    name: 'ICT Data Protection',
    description: 'Verify data protection mechanisms for ICT systems',
    regulation: 'DORA',
    articles: ['Art.9'],
    category: 'DATA_PROTECTION',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'encryption', type: 'CONTROL', filters: { control_type: 'ENCRYPTION' } },
        { alias: 'backup', type: 'CONTROL', filters: { control_type: 'BACKUP' } },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'encryption-active',
        description: 'Encryption controls active',
        type: 'VALUE',
        params: { nodeAlias: 'encryption', field: 'status', operator: 'EQUALS', value: 'ACTIVE' },
        weight: 50,
        mandatory: true,
      },
      {
        id: 'backup-active',
        description: 'Backup controls active',
        type: 'VALUE',
        params: { nodeAlias: 'backup', field: 'status', operator: 'EQUALS', value: 'ACTIVE' },
        weight: 50,
        mandatory: true,
      },
    ],
  },
  {
    queryId: 'DORA-10-DETECTION',
    name: 'ICT Anomaly Detection',
    description: 'Verify detection mechanisms for ICT anomalies',
    regulation: 'DORA',
    articles: ['Art.10'],
    category: 'MONITORING',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'monitoring', type: 'CONTROL', filters: { control_type: 'MONITORING' } },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'monitoring-active',
        description: 'Monitoring controls are active',
        type: 'VALUE',
        params: { nodeAlias: 'monitoring', field: 'status', operator: 'EQUALS', value: 'ACTIVE' },
        weight: 60,
        mandatory: true,
      },
      {
        id: 'recently-used',
        description: 'Monitoring was recently active',
        type: 'TIMING',
        params: { nodeAlias: 'monitoring', field: 'last_used_at', withinHours: 24 },
        weight: 40,
        mandatory: false,
      },
    ],
  },
  {
    queryId: 'DORA-11-RESPONSE',
    name: 'ICT Incident Response',
    description: 'Verify incident response capabilities',
    regulation: 'DORA',
    articles: ['Art.11'],
    category: 'INCIDENT_MANAGEMENT',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'response', type: 'CONTROL', filters: { control_type: 'INCIDENT_RESPONSE' } },
        { alias: 'incident', type: 'EVENT', filters: { event_type: 'INCIDENT.CREATED' } },
        { alias: 'resolution', type: 'EVENT', filters: { event_type: 'INCIDENT.RESOLVED' }, optional: true },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'response-capability',
        description: 'Incident response control exists',
        type: 'VALUE',
        params: { nodeAlias: 'response', field: 'status', operator: 'EQUALS', value: 'ACTIVE' },
        weight: 50,
        mandatory: true,
      },
      {
        id: 'incidents-resolved',
        description: 'Incidents are being resolved',
        type: 'EXISTS',
        params: { nodeAlias: 'resolution' },
        weight: 50,
        mandatory: false,
      },
    ],
  },
  {
    queryId: 'DORA-12-BACKUP',
    name: 'ICT Backup and Recovery',
    description: 'Verify backup and recovery policies',
    regulation: 'DORA',
    articles: ['Art.12'],
    category: 'DATA_PROTECTION',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'backup', type: 'CONTROL', filters: { control_type: 'BACKUP' } },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'backup-active',
        description: 'Backup controls are active',
        type: 'VALUE',
        params: { nodeAlias: 'backup', field: 'status', operator: 'EQUALS', value: 'ACTIVE' },
        weight: 60,
        mandatory: true,
      },
      {
        id: 'backup-tested',
        description: 'Backups were tested recently',
        type: 'TIMING',
        params: { nodeAlias: 'backup', field: 'last_tested_at', withinHours: 2160 },
        weight: 40,
        mandatory: false,
      },
    ],
  },
  {
    queryId: 'DORA-13-LEARNING',
    name: 'ICT Incident Learning',
    description: 'Verify lessons learned from ICT incidents',
    regulation: 'DORA',
    articles: ['Art.13'],
    category: 'INCIDENT_MANAGEMENT',
    severity: 'MEDIUM',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'pattern', type: 'EVENT', filters: { event_type: 'INCIDENT.PATTERN.DETECTED' }, optional: true },
        { alias: 'recommendation', type: 'EVENT', filters: { event_type: 'INCIDENT.RECOMMENDATION.GENERATED' }, optional: true },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'pattern-analysis',
        description: 'Pattern analysis is performed',
        type: 'EXISTS',
        params: { nodeAlias: 'pattern' },
        weight: 50,
        mandatory: false,
      },
      {
        id: 'recommendations',
        description: 'Improvement recommendations exist',
        type: 'EXISTS',
        params: { nodeAlias: 'recommendation' },
        weight: 50,
        mandatory: false,
      },
    ],
  },
  {
    queryId: 'DORA-14-COMMUNICATION',
    name: 'ICT Incident Communication',
    description: 'Verify incident communication to stakeholders',
    regulation: 'DORA',
    articles: ['Art.14'],
    category: 'INCIDENT_MANAGEMENT',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'incident', type: 'EVENT', filters: { event_type: 'INCIDENT.CREATED' } },
        { alias: 'communication', type: 'EVENT', filters: { event_type: 'COMMUNICATION.SENT' } },
        { alias: 'ack', type: 'EVENT', filters: { event_type: 'COMMUNICATION.ACKNOWLEDGED' }, optional: true },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'communication-sent',
        description: 'Stakeholder communication was sent',
        type: 'EXISTS',
        params: { nodeAlias: 'communication' },
        weight: 60,
        mandatory: true,
      },
      {
        id: 'communication-acked',
        description: 'Communication was acknowledged',
        type: 'EXISTS',
        params: { nodeAlias: 'ack' },
        weight: 40,
        mandatory: false,
      },
    ],
  },
  {
    queryId: 'DORA-28-TPRM-POLICY',
    name: 'Third-Party Risk Management Policy',
    description: 'Verify TPRM policy exists and is approved',
    regulation: 'DORA',
    articles: ['Art.28'],
    category: 'VENDOR_MANAGEMENT',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'policy', type: 'EVENT', filters: { event_type: 'GOVERNANCE.POLICY.CREATED', 'payload.category': 'TPRM' } },
        { alias: 'approval', type: 'DECISION', filters: { decision_type: 'APPROVAL' } },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'tprm-policy',
        description: 'TPRM policy exists',
        type: 'EXISTS',
        params: { nodeAlias: 'policy' },
        weight: 60,
        mandatory: true,
      },
      {
        id: 'policy-approved',
        description: 'Policy is approved',
        type: 'EXISTS',
        params: { nodeAlias: 'approval' },
        weight: 40,
        mandatory: false,
      },
    ],
  },
  {
    queryId: 'DORA-29-VENDOR-ASSESSMENT',
    name: 'ICT Third-Party Assessment',
    description: 'Verify ICT third parties are risk assessed',
    regulation: 'DORA',
    articles: ['Art.29'],
    category: 'VENDOR_MANAGEMENT',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'vendor', type: 'EVENT', filters: { event_type: 'VENDOR.REGISTERED' } },
        { alias: 'assessment', type: 'EVENT', filters: { event_type: 'VENDOR.RISK_ASSESSED' } },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'vendors-registered',
        description: 'Vendors are registered',
        type: 'EXISTS',
        params: { nodeAlias: 'vendor' },
        weight: 40,
        mandatory: true,
      },
      {
        id: 'vendors-assessed',
        description: 'Vendors are risk assessed',
        type: 'EXISTS',
        params: { nodeAlias: 'assessment' },
        weight: 60,
        mandatory: true,
      },
    ],
  },
  {
    queryId: 'DORA-30-CRITICAL-PROVIDERS',
    name: 'Critical ICT Third-Party Providers',
    description: 'Verify critical providers have enhanced oversight',
    regulation: 'DORA',
    articles: ['Art.30'],
    category: 'VENDOR_MANAGEMENT',
    severity: 'CRITICAL',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'critical_vendor', type: 'EVENT', filters: { event_type: 'VENDOR.REGISTERED', 'payload.criticality': 'CRITICAL' } },
        { alias: 'assessment', type: 'EVENT', filters: { event_type: 'VENDOR.RISK_ASSESSED' } },
      ],
      requiredEdges: [],
      timeConstraints: [
        { field: 'assessment.occurred_at', within: '6_MONTHS' },
      ],
    },
    proofCriteria: [
      {
        id: 'critical-identified',
        description: 'Critical providers are identified',
        type: 'EXISTS',
        params: { nodeAlias: 'critical_vendor' },
        weight: 50,
        mandatory: true,
      },
      {
        id: 'recent-assessment',
        description: 'Critical providers assessed within 6 months',
        type: 'TIMING',
        params: { nodeAlias: 'assessment', field: 'occurred_at', withinHours: 4320 },
        weight: 50,
        mandatory: true,
      },
    ],
  },
];

// ═══════════════════════════════════════════════════════════════
// GDPR QUERIES (12)
// ═══════════════════════════════════════════════════════════════

export const GDPR_QUERIES: ComplianceQuery[] = [
  {
    queryId: 'GDPR-33-BREACH-NOTIFICATION',
    name: 'Breach Notification to DPA (72h)',
    description: 'Verify that data breaches are reported to the supervisory authority within 72 hours',
    regulation: 'GDPR',
    articles: ['Art.33'],
    category: 'BREACH_NOTIFICATION',
    severity: 'CRITICAL',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'breach', type: 'EVENT', filters: { event_type: { contains: 'BREACH' } } },
        { alias: 'clock', type: 'CLOCK', filters: { clock_type: 'GDPR_72H' } },
        { alias: 'notification', type: 'EVENT', filters: { event_type: 'BREACH.NOTIFIED_DPA' }, optional: true },
        { alias: 'artifact', type: 'ARTIFACT', filters: { artifact_type: 'NOTIFICATION_PROOF' }, optional: true },
      ],
      requiredEdges: [
        { type: 'TRIGGERS', from: 'breach', to: 'clock' },
      ],
    },
    proofCriteria: [
      {
        id: 'clock-met',
        description: 'GDPR 72h clock was met (not breached)',
        type: 'VALUE',
        params: { nodeAlias: 'clock', field: 'status', operator: 'IN', value: ['MET', 'STOPPED'] },
        weight: 50,
        mandatory: true,
      },
      {
        id: 'notification-sent',
        description: 'DPA notification event exists',
        type: 'EXISTS',
        params: { nodeAlias: 'notification' },
        weight: 30,
        mandatory: true,
      },
      {
        id: 'artifact-exists',
        description: 'Notification proof artifact exists',
        type: 'EXISTS',
        params: { nodeAlias: 'artifact' },
        weight: 20,
        mandatory: false,
      },
    ],
  },
  {
    queryId: 'GDPR-34-SUBJECT-NOTIFICATION',
    name: 'Data Subject Notification (High Risk)',
    description: 'Verify that affected data subjects are notified of high-risk breaches',
    regulation: 'GDPR',
    articles: ['Art.34'],
    category: 'BREACH_NOTIFICATION',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'breach', type: 'EVENT', filters: { event_type: 'BREACH.DETECTED', 'payload.severity': 'CRITICAL' } },
        { alias: 'notification', type: 'EVENT', filters: { event_type: 'BREACH.NOTIFIED_SUBJECTS' }, optional: true },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'subjects-notified',
        description: 'Data subjects were notified',
        type: 'EXISTS',
        params: { nodeAlias: 'notification' },
        weight: 100,
        mandatory: true,
      },
    ],
  },
  {
    queryId: 'GDPR-30-RECORDS',
    name: 'Records of Processing Activities',
    description: 'Verify that records of processing activities are maintained',
    regulation: 'GDPR',
    articles: ['Art.30'],
    category: 'DOCUMENTATION',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'records', type: 'ARTIFACT', filters: { artifact_type: { in: ['EXPORT_PACKAGE', 'REPORT'] }, 'metadata.type': 'ROPA' }, minCount: 1 },
      ],
      requiredEdges: [],
      timeConstraints: [
        { field: 'records.created_at', within: '12_MONTHS' },
      ],
    },
    proofCriteria: [
      {
        id: 'ropa-exists',
        description: 'Records of Processing Activities document exists',
        type: 'EXISTS',
        params: { nodeAlias: 'records' },
        weight: 60,
        mandatory: true,
      },
      {
        id: 'ropa-recent',
        description: 'ROPA was updated within 12 months',
        type: 'TIMING',
        params: { nodeAlias: 'records', field: 'created_at', withinHours: 8760 },
        weight: 40,
        mandatory: false,
      },
    ],
  },
  {
    queryId: 'GDPR-35-DPIA',
    name: 'Data Protection Impact Assessment',
    description: 'Verify that DPIAs are conducted for high-risk processing',
    regulation: 'GDPR',
    articles: ['Art.35'],
    category: 'RISK_MANAGEMENT',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'dpia', type: 'ARTIFACT', filters: { artifact_type: 'REPORT', 'metadata.type': 'DPIA' } },
        { alias: 'approval', type: 'DECISION', filters: { decision_type: 'APPROVAL' }, optional: true },
      ],
      requiredEdges: [],
      timeConstraints: [
        { field: 'dpia.created_at', within: '12_MONTHS' },
      ],
    },
    proofCriteria: [
      {
        id: 'dpia-exists',
        description: 'DPIA document exists',
        type: 'EXISTS',
        params: { nodeAlias: 'dpia' },
        weight: 50,
        mandatory: true,
      },
      {
        id: 'dpia-approved',
        description: 'DPIA was formally approved',
        type: 'EXISTS',
        params: { nodeAlias: 'approval' },
        weight: 50,
        mandatory: false,
      },
    ],
  },
  {
    queryId: 'GDPR-6-LAWFUL-BASIS',
    name: 'Lawful Basis Documentation',
    description: 'Verify that lawful basis for processing is documented',
    regulation: 'GDPR',
    articles: ['Art.6'],
    category: 'DATA_PROTECTION',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'consent', type: 'EVENT', filters: { event_type: 'CONSENT.RECORDED' }, minCount: 1 },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'consent-recorded',
        description: 'Consent records exist',
        type: 'COUNT',
        params: { nodeAlias: 'consent', minCount: 1 },
        weight: 100,
        mandatory: true,
      },
    ],
  },
  {
    queryId: 'GDPR-7-CONSENT-CONDITIONS',
    name: 'Consent Conditions',
    description: 'Verify that consent meets GDPR requirements',
    regulation: 'GDPR',
    articles: ['Art.7'],
    category: 'DATA_PROTECTION',
    severity: 'MEDIUM',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'consent', type: 'EVENT', filters: { event_type: 'CONSENT.RECORDED' } },
        { alias: 'artifact', type: 'ARTIFACT', filters: { 'metadata.consentProof': true }, optional: true },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'consent-documented',
        description: 'Consent is properly documented',
        type: 'EXISTS',
        params: { nodeAlias: 'consent' },
        weight: 70,
        mandatory: true,
      },
      {
        id: 'consent-proof',
        description: 'Consent proof artifact exists',
        type: 'EXISTS',
        params: { nodeAlias: 'artifact' },
        weight: 30,
        mandatory: false,
      },
    ],
  },
  {
    queryId: 'GDPR-15-ACCESS-RIGHTS',
    name: 'Right of Access Handling',
    description: 'Verify that data subject access requests are handled within 30 days',
    regulation: 'GDPR',
    articles: ['Art.15'],
    category: 'DATA_PROTECTION',
    severity: 'MEDIUM',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'request', type: 'EVENT', filters: { event_type: 'DSR.RECEIVED', 'payload.requestType': 'ACCESS' } },
        { alias: 'response', type: 'EVENT', filters: { event_type: 'DSR.COMPLETED' }, optional: true },
        { alias: 'clock', type: 'CLOCK', filters: { clock_type: 'CUSTOM' }, optional: true },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'request-completed',
        description: 'Access request was completed',
        type: 'EXISTS',
        params: { nodeAlias: 'response' },
        weight: 60,
        mandatory: true,
      },
      {
        id: 'within-deadline',
        description: 'Completed within 30 days',
        type: 'VALUE',
        params: { nodeAlias: 'clock', field: 'status', operator: 'EQUALS', value: 'MET' },
        weight: 40,
        mandatory: false,
      },
    ],
  },
  {
    queryId: 'GDPR-17-ERASURE',
    name: 'Right to Erasure Handling',
    description: 'Verify that erasure requests are properly handled',
    regulation: 'GDPR',
    articles: ['Art.17'],
    category: 'DATA_PROTECTION',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'request', type: 'EVENT', filters: { event_type: 'DSR.RECEIVED', 'payload.requestType': 'ERASURE' } },
        { alias: 'execution', type: 'EVENT', filters: { event_type: 'DSR.COMPLETED' }, optional: true },
        { alias: 'artifact', type: 'ARTIFACT', filters: { 'metadata.erasureProof': true }, optional: true },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'erasure-completed',
        description: 'Erasure was executed',
        type: 'EXISTS',
        params: { nodeAlias: 'execution' },
        weight: 50,
        mandatory: true,
      },
      {
        id: 'erasure-proof',
        description: 'Erasure proof artifact exists',
        type: 'EXISTS',
        params: { nodeAlias: 'artifact' },
        weight: 50,
        mandatory: false,
      },
    ],
  },
  {
    queryId: 'GDPR-20-PORTABILITY',
    name: 'Right to Data Portability',
    description: 'Verify that data portability requests are handled',
    regulation: 'GDPR',
    articles: ['Art.20'],
    category: 'DATA_PROTECTION',
    severity: 'MEDIUM',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'request', type: 'EVENT', filters: { event_type: 'DSR.RECEIVED', 'payload.requestType': 'PORTABILITY' } },
        { alias: 'export', type: 'ARTIFACT', filters: { artifact_type: 'EXPORT_PACKAGE' }, optional: true },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'export-created',
        description: 'Data export was created',
        type: 'EXISTS',
        params: { nodeAlias: 'export' },
        weight: 100,
        mandatory: true,
      },
    ],
  },
  {
    queryId: 'GDPR-25-DPbD',
    name: 'Data Protection by Design',
    description: 'Verify implementation of privacy by design principles',
    regulation: 'GDPR',
    articles: ['Art.25'],
    category: 'DATA_PROTECTION',
    severity: 'MEDIUM',
    automatable: false,
    query: {
      requiredNodes: [
        { alias: 'control', type: 'CONTROL', filters: { control_type: 'DATA_PROTECTION' } },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'control-active',
        description: 'Data protection controls are active',
        type: 'VALUE',
        params: { nodeAlias: 'control', field: 'status', operator: 'EQUALS', value: 'ACTIVE' },
        weight: 50,
        mandatory: true,
      },
      {
        id: 'control-tested',
        description: 'Controls were tested recently',
        type: 'TIMING',
        params: { nodeAlias: 'control', field: 'last_tested_at', withinHours: 8760 },
        weight: 50,
        mandatory: false,
      },
    ],
  },
  {
    queryId: 'GDPR-32-SECURITY',
    name: 'Security of Processing',
    description: 'Verify appropriate security measures are in place',
    regulation: 'GDPR',
    articles: ['Art.32'],
    category: 'DATA_PROTECTION',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'encryption', type: 'CONTROL', filters: { control_type: 'ENCRYPTION' } },
        { alias: 'access', type: 'CONTROL', filters: { control_type: 'ACCESS_CONTROL' } },
        { alias: 'backup', type: 'CONTROL', filters: { control_type: 'BACKUP' } },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'encryption-active',
        description: 'Encryption controls active',
        type: 'VALUE',
        params: { nodeAlias: 'encryption', field: 'status', operator: 'EQUALS', value: 'ACTIVE' },
        weight: 40,
        mandatory: false,
      },
      {
        id: 'access-control-active',
        description: 'Access control is active',
        type: 'VALUE',
        params: { nodeAlias: 'access', field: 'status', operator: 'EQUALS', value: 'ACTIVE' },
        weight: 40,
        mandatory: true,
      },
      {
        id: 'backup-active',
        description: 'Backup controls are active',
        type: 'VALUE',
        params: { nodeAlias: 'backup', field: 'status', operator: 'EQUALS', value: 'ACTIVE' },
        weight: 20,
        mandatory: false,
      },
    ],
  },
  {
    queryId: 'GDPR-44-TRANSFERS',
    name: 'International Data Transfers',
    description: 'Verify lawful basis for international data transfers',
    regulation: 'GDPR',
    articles: ['Art.44', 'Art.45', 'Art.46'],
    category: 'DATA_PROTECTION',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'transfer', type: 'EVENT', filters: { event_type: { contains: 'TRANSFER' } } },
        { alias: 'decision', type: 'DECISION', filters: { decision_type: 'APPROVAL' }, optional: true },
        { alias: 'artifact', type: 'ARTIFACT', filters: { 'metadata.transferBasis': true }, optional: true },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'transfer-approved',
        description: 'Transfer has legal basis approval',
        type: 'EXISTS',
        params: { nodeAlias: 'decision' },
        weight: 60,
        mandatory: true,
      },
      {
        id: 'documentation-exists',
        description: 'Transfer documentation exists',
        type: 'EXISTS',
        params: { nodeAlias: 'artifact' },
        weight: 40,
        mandatory: false,
      },
    ],
  },
];

// ═══════════════════════════════════════════════════════════════
// NIS2 QUERIES (10)
// ═══════════════════════════════════════════════════════════════

export const NIS2_QUERIES: ComplianceQuery[] = [
  {
    queryId: 'NIS2-20-MANAGEMENT-ACCOUNTABILITY',
    name: 'Management Body Accountability',
    description: 'Verify management body oversight of cybersecurity',
    regulation: 'NIS2',
    articles: ['Art.20'],
    category: 'GOVERNANCE',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'oversight', type: 'EVENT', filters: { event_type: 'GOVERNANCE.OVERSIGHT.RECORDED' } },
        { alias: 'executive', type: 'ACTOR', filters: { authority_level: { in: ['EXECUTIVE', 'BOARD'] } } },
        { alias: 'approval', type: 'DECISION', filters: { decision_type: 'APPROVAL' } },
      ],
      requiredEdges: [
        { type: 'MADE_BY', from: 'approval', to: 'executive' },
      ],
      timeConstraints: [
        { field: 'oversight.occurred_at', within: '12_MONTHS' },
      ],
    },
    proofCriteria: [
      {
        id: 'oversight-recorded',
        description: 'Management oversight activities recorded',
        type: 'EXISTS',
        params: { nodeAlias: 'oversight' },
        weight: 40,
        mandatory: true,
      },
      {
        id: 'executive-approval',
        description: 'Executive level approvals exist',
        type: 'EXISTS',
        params: { nodeAlias: 'approval' },
        weight: 40,
        mandatory: true,
      },
      {
        id: 'recent-activity',
        description: 'Recent oversight activity',
        type: 'TIMING',
        params: { nodeAlias: 'oversight', field: 'occurred_at', withinHours: 2160 },
        weight: 20,
        mandatory: false,
      },
    ],
  },
  {
    queryId: 'NIS2-21-SECURITY-MEASURES',
    name: 'Cybersecurity Risk Management Measures',
    description: 'Verify appropriate security measures are implemented',
    regulation: 'NIS2',
    articles: ['Art.21'],
    category: 'RISK_MANAGEMENT',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'incident_response', type: 'CONTROL', filters: { control_type: 'INCIDENT_RESPONSE' } },
        { alias: 'access_control', type: 'CONTROL', filters: { control_type: 'ACCESS_CONTROL' } },
        { alias: 'encryption', type: 'CONTROL', filters: { control_type: 'ENCRYPTION' } },
        { alias: 'backup', type: 'CONTROL', filters: { control_type: 'BACKUP' } },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'incident-response',
        description: 'Incident response controls active',
        type: 'VALUE',
        params: { nodeAlias: 'incident_response', field: 'status', operator: 'EQUALS', value: 'ACTIVE' },
        weight: 25,
        mandatory: true,
      },
      {
        id: 'access-control',
        description: 'Access control active',
        type: 'VALUE',
        params: { nodeAlias: 'access_control', field: 'status', operator: 'EQUALS', value: 'ACTIVE' },
        weight: 25,
        mandatory: true,
      },
      {
        id: 'encryption',
        description: 'Encryption active',
        type: 'VALUE',
        params: { nodeAlias: 'encryption', field: 'status', operator: 'EQUALS', value: 'ACTIVE' },
        weight: 25,
        mandatory: true,
      },
      {
        id: 'backup',
        description: 'Backup active',
        type: 'VALUE',
        params: { nodeAlias: 'backup', field: 'status', operator: 'EQUALS', value: 'ACTIVE' },
        weight: 25,
        mandatory: false,
      },
    ],
  },
  {
    queryId: 'NIS2-23-INCIDENT-NOTIFICATION-24H',
    name: 'Incident Early Warning (24h)',
    description: 'Verify early warning notifications within 24 hours',
    regulation: 'NIS2',
    articles: ['Art.23'],
    category: 'INCIDENT_MANAGEMENT',
    severity: 'CRITICAL',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'incident', type: 'EVENT', filters: { event_type: 'INCIDENT.CREATED', severity: { in: ['CRITICAL', 'HIGH'] } } },
        { alias: 'clock', type: 'CLOCK', filters: { clock_type: 'NIS2_24H' } },
        { alias: 'notification', type: 'EVENT', filters: { event_type: 'COMMUNICATION.SENT' }, optional: true },
      ],
      requiredEdges: [
        { type: 'TRIGGERS', from: 'incident', to: 'clock' },
      ],
    },
    proofCriteria: [
      {
        id: 'clock-met',
        description: '24-hour early warning deadline met',
        type: 'VALUE',
        params: { nodeAlias: 'clock', field: 'status', operator: 'IN', value: ['MET', 'STOPPED'] },
        weight: 70,
        mandatory: true,
      },
      {
        id: 'notification-sent',
        description: 'Early warning notification sent',
        type: 'EXISTS',
        params: { nodeAlias: 'notification' },
        weight: 30,
        mandatory: false,
      },
    ],
  },
  {
    queryId: 'NIS2-23-INCIDENT-NOTIFICATION-72H',
    name: 'Incident Notification (72h)',
    description: 'Verify incident notifications within 72 hours',
    regulation: 'NIS2',
    articles: ['Art.23'],
    category: 'INCIDENT_MANAGEMENT',
    severity: 'CRITICAL',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'incident', type: 'EVENT', filters: { event_type: 'INCIDENT.CREATED' } },
        { alias: 'clock', type: 'CLOCK', filters: { clock_type: 'NIS2_72H' } },
      ],
      requiredEdges: [
        { type: 'TRIGGERS', from: 'incident', to: 'clock' },
      ],
    },
    proofCriteria: [
      {
        id: 'clock-met',
        description: '72-hour notification deadline met',
        type: 'VALUE',
        params: { nodeAlias: 'clock', field: 'status', operator: 'IN', value: ['MET', 'STOPPED'] },
        weight: 100,
        mandatory: true,
      },
    ],
  },
  {
    queryId: 'NIS2-23-FINAL-REPORT',
    name: 'Incident Final Report (1 month)',
    description: 'Verify final incident reports within 1 month',
    regulation: 'NIS2',
    articles: ['Art.23'],
    category: 'INCIDENT_MANAGEMENT',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'incident', type: 'EVENT', filters: { event_type: 'INCIDENT.CREATED' } },
        { alias: 'clock', type: 'CLOCK', filters: { clock_type: 'NIS2_1M' } },
        { alias: 'report', type: 'ARTIFACT', filters: { artifact_type: 'REPORT' }, optional: true },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'clock-met',
        description: '1-month final report deadline met',
        type: 'VALUE',
        params: { nodeAlias: 'clock', field: 'status', operator: 'IN', value: ['MET', 'STOPPED'] },
        weight: 60,
        mandatory: true,
      },
      {
        id: 'report-exists',
        description: 'Final report artifact exists',
        type: 'EXISTS',
        params: { nodeAlias: 'report' },
        weight: 40,
        mandatory: false,
      },
    ],
  },
  {
    queryId: 'NIS2-21-SUPPLY-CHAIN',
    name: 'Supply Chain Security',
    description: 'Verify supply chain security measures',
    regulation: 'NIS2',
    articles: ['Art.21'],
    category: 'VENDOR_MANAGEMENT',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'vendor', type: 'EVENT', filters: { event_type: 'VENDOR.REGISTERED' } },
        { alias: 'assessment', type: 'EVENT', filters: { event_type: 'VENDOR.RISK_ASSESSED' } },
        { alias: 'control', type: 'CONTROL', filters: { control_type: 'VENDOR_MANAGEMENT' }, optional: true },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'vendors-tracked',
        description: 'Supply chain vendors are tracked',
        type: 'EXISTS',
        params: { nodeAlias: 'vendor' },
        weight: 40,
        mandatory: true,
      },
      {
        id: 'vendors-assessed',
        description: 'Vendors are risk assessed',
        type: 'EXISTS',
        params: { nodeAlias: 'assessment' },
        weight: 40,
        mandatory: true,
      },
      {
        id: 'control-active',
        description: 'Vendor management control active',
        type: 'VALUE',
        params: { nodeAlias: 'control', field: 'status', operator: 'EQUALS', value: 'ACTIVE' },
        weight: 20,
        mandatory: false,
      },
    ],
  },
  {
    queryId: 'NIS2-21-NETWORK-SECURITY',
    name: 'Network and Information System Security',
    description: 'Verify network security measures',
    regulation: 'NIS2',
    articles: ['Art.21'],
    category: 'DATA_PROTECTION',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'network', type: 'CONTROL', filters: { control_type: 'NETWORK_SECURITY' } },
        { alias: 'monitoring', type: 'CONTROL', filters: { control_type: 'MONITORING' } },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'network-security',
        description: 'Network security controls active',
        type: 'VALUE',
        params: { nodeAlias: 'network', field: 'status', operator: 'EQUALS', value: 'ACTIVE' },
        weight: 50,
        mandatory: true,
      },
      {
        id: 'monitoring',
        description: 'Network monitoring active',
        type: 'VALUE',
        params: { nodeAlias: 'monitoring', field: 'status', operator: 'EQUALS', value: 'ACTIVE' },
        weight: 50,
        mandatory: true,
      },
    ],
  },
  {
    queryId: 'NIS2-21-INCIDENT-HANDLING',
    name: 'Incident Handling Procedures',
    description: 'Verify incident handling procedures are in place',
    regulation: 'NIS2',
    articles: ['Art.21'],
    category: 'INCIDENT_MANAGEMENT',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'response', type: 'CONTROL', filters: { control_type: 'INCIDENT_RESPONSE' } },
        { alias: 'escalation', type: 'CONTROL', filters: { control_type: 'ESCALATION_POLICY' }, optional: true },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'response-active',
        description: 'Incident response procedures active',
        type: 'VALUE',
        params: { nodeAlias: 'response', field: 'status', operator: 'EQUALS', value: 'ACTIVE' },
        weight: 60,
        mandatory: true,
      },
      {
        id: 'escalation-active',
        description: 'Escalation policy active',
        type: 'VALUE',
        params: { nodeAlias: 'escalation', field: 'status', operator: 'EQUALS', value: 'ACTIVE' },
        weight: 40,
        mandatory: false,
      },
    ],
  },
  {
    queryId: 'NIS2-21-BUSINESS-CONTINUITY',
    name: 'Business Continuity',
    description: 'Verify business continuity measures',
    regulation: 'NIS2',
    articles: ['Art.21'],
    category: 'DATA_PROTECTION',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'backup', type: 'CONTROL', filters: { control_type: 'BACKUP' } },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'backup-active',
        description: 'Business continuity/backup controls active',
        type: 'VALUE',
        params: { nodeAlias: 'backup', field: 'status', operator: 'EQUALS', value: 'ACTIVE' },
        weight: 60,
        mandatory: true,
      },
      {
        id: 'backup-tested',
        description: 'Backup tested recently',
        type: 'TIMING',
        params: { nodeAlias: 'backup', field: 'last_tested_at', withinHours: 2160 },
        weight: 40,
        mandatory: false,
      },
    ],
  },
  {
    queryId: 'NIS2-21-HR-SECURITY',
    name: 'Human Resources Security',
    description: 'Verify HR security measures and training',
    regulation: 'NIS2',
    articles: ['Art.21'],
    category: 'GOVERNANCE',
    severity: 'MEDIUM',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'training', type: 'EVENT', filters: { event_type: 'GOVERNANCE.TRAINING.COMPLETED' }, optional: true },
        { alias: 'access', type: 'CONTROL', filters: { control_type: 'ACCESS_CONTROL' } },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'access-control',
        description: 'Access control is active',
        type: 'VALUE',
        params: { nodeAlias: 'access', field: 'status', operator: 'EQUALS', value: 'ACTIVE' },
        weight: 60,
        mandatory: true,
      },
      {
        id: 'training-conducted',
        description: 'Security training conducted',
        type: 'EXISTS',
        params: { nodeAlias: 'training' },
        weight: 40,
        mandatory: false,
      },
    ],
  },
];

// ═══════════════════════════════════════════════════════════════
// AI ACT QUERIES (8)
// ═══════════════════════════════════════════════════════════════

export const AI_ACT_QUERIES: ComplianceQuery[] = [
  {
    queryId: 'AI-ACT-5-PROHIBITED-PRACTICES',
    name: 'Prohibited AI Practices',
    description: 'Verify no prohibited AI practices are deployed',
    regulation: 'AI_ACT',
    articles: ['Art.5'],
    category: 'AI_OVERSIGHT',
    severity: 'CRITICAL',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'blocked', type: 'EVENT', filters: { event_type: 'AI.BLOCKED.PROHIBITED' }, optional: true },
        { alias: 'control', type: 'CONTROL', filters: { control_type: 'AI_OVERSIGHT' } },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'oversight-active',
        description: 'AI oversight control is active',
        type: 'VALUE',
        params: { nodeAlias: 'control', field: 'status', operator: 'EQUALS', value: 'ACTIVE' },
        weight: 60,
        mandatory: true,
      },
      {
        id: 'blocking-works',
        description: 'Prohibited practices are being blocked',
        type: 'EXISTS',
        params: { nodeAlias: 'blocked' },
        weight: 40,
        mandatory: false,
      },
    ],
  },
  {
    queryId: 'AI-ACT-14-HUMAN-OVERSIGHT',
    name: 'Human Oversight of AI Systems',
    description: 'Verify human oversight capability for AI systems',
    regulation: 'AI_ACT',
    articles: ['Art.14'],
    category: 'AI_OVERSIGHT',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'ai_decision', type: 'EVENT', filters: { event_type: 'AI.DECISION.MADE' } },
        { alias: 'override', type: 'EVENT', filters: { event_type: 'AI.OVERRIDE.EXECUTED' }, optional: true },
        { alias: 'human', type: 'ACTOR', filters: { actor_type: 'USER' } },
        { alias: 'control', type: 'CONTROL', filters: { control_type: 'AI_OVERSIGHT' } },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'oversight-active',
        description: 'AI oversight control is active',
        type: 'VALUE',
        params: { nodeAlias: 'control', field: 'status', operator: 'EQUALS', value: 'ACTIVE' },
        weight: 40,
        mandatory: true,
      },
      {
        id: 'override-capability',
        description: 'Human override capability exists',
        type: 'EXISTS',
        params: { nodeAlias: 'override' },
        weight: 40,
        mandatory: false,
      },
      {
        id: 'human-actor',
        description: 'Human actors in oversight loop',
        type: 'EXISTS',
        params: { nodeAlias: 'human' },
        weight: 20,
        mandatory: false,
      },
    ],
  },
  {
    queryId: 'AI-ACT-13-TRANSPARENCY',
    name: 'AI System Transparency',
    description: 'Verify transparency requirements for AI systems',
    regulation: 'AI_ACT',
    articles: ['Art.13'],
    category: 'AI_OVERSIGHT',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'disclosure', type: 'EVENT', filters: { event_type: 'AI.TRANSPARENCY.DISCLOSED' }, optional: true },
        { alias: 'artifact', type: 'ARTIFACT', filters: { 'metadata.aiTransparency': true }, optional: true },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'disclosure-exists',
        description: 'Transparency disclosures exist',
        type: 'EXISTS',
        params: { nodeAlias: 'disclosure' },
        weight: 60,
        mandatory: false,
      },
      {
        id: 'documentation',
        description: 'Transparency documentation exists',
        type: 'EXISTS',
        params: { nodeAlias: 'artifact' },
        weight: 40,
        mandatory: false,
      },
    ],
  },
  {
    queryId: 'AI-ACT-9-RISK-MANAGEMENT',
    name: 'AI Risk Management System',
    description: 'Verify risk management for high-risk AI systems',
    regulation: 'AI_ACT',
    articles: ['Art.9'],
    category: 'RISK_MANAGEMENT',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'risk_assessment', type: 'EVENT', filters: { event_type: 'RISK.ASSESSMENT.COMPLETED', 'regulatory_tags': { has: 'AI_ACT' } } },
        { alias: 'control', type: 'CONTROL', filters: { control_type: 'AI_OVERSIGHT' } },
      ],
      requiredEdges: [],
      timeConstraints: [
        { field: 'risk_assessment.occurred_at', within: '12_MONTHS' },
      ],
    },
    proofCriteria: [
      {
        id: 'risk-assessed',
        description: 'AI risk assessment conducted',
        type: 'EXISTS',
        params: { nodeAlias: 'risk_assessment' },
        weight: 60,
        mandatory: true,
      },
      {
        id: 'control-active',
        description: 'AI oversight control active',
        type: 'VALUE',
        params: { nodeAlias: 'control', field: 'status', operator: 'EQUALS', value: 'ACTIVE' },
        weight: 40,
        mandatory: true,
      },
    ],
  },
  {
    queryId: 'AI-ACT-11-TECHNICAL-DOCUMENTATION',
    name: 'AI Technical Documentation',
    description: 'Verify technical documentation for AI systems',
    regulation: 'AI_ACT',
    articles: ['Art.11'],
    category: 'DOCUMENTATION',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'docs', type: 'ARTIFACT', filters: { artifact_type: { in: ['REPORT', 'EXPORT_PACKAGE'] }, 'metadata.aiDocumentation': true } },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'documentation-exists',
        description: 'AI technical documentation exists',
        type: 'EXISTS',
        params: { nodeAlias: 'docs' },
        weight: 100,
        mandatory: true,
      },
    ],
  },
  {
    queryId: 'AI-ACT-12-RECORD-KEEPING',
    name: 'AI System Record Keeping',
    description: 'Verify record keeping for AI system operations',
    regulation: 'AI_ACT',
    articles: ['Art.12'],
    category: 'DOCUMENTATION',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'ai_events', type: 'EVENT', filters: { event_type: { contains: 'AI.' } }, minCount: 1 },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'records-exist',
        description: 'AI operation records exist',
        type: 'COUNT',
        params: { nodeAlias: 'ai_events', minCount: 1 },
        weight: 100,
        mandatory: true,
      },
    ],
  },
  {
    queryId: 'AI-ACT-15-ACCURACY',
    name: 'AI System Accuracy Monitoring',
    description: 'Verify accuracy and performance monitoring',
    regulation: 'AI_ACT',
    articles: ['Art.15'],
    category: 'MONITORING',
    severity: 'HIGH',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'monitoring', type: 'CONTROL', filters: { control_type: 'MONITORING' } },
        { alias: 'performance', type: 'EVENT', filters: { event_type: { contains: 'AI.PERFORMANCE' } }, optional: true },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'monitoring-active',
        description: 'AI monitoring is active',
        type: 'VALUE',
        params: { nodeAlias: 'monitoring', field: 'status', operator: 'EQUALS', value: 'ACTIVE' },
        weight: 60,
        mandatory: true,
      },
      {
        id: 'performance-tracked',
        description: 'Performance events are tracked',
        type: 'EXISTS',
        params: { nodeAlias: 'performance' },
        weight: 40,
        mandatory: false,
      },
    ],
  },
  {
    queryId: 'AI-ACT-52-CHATBOT-DISCLOSURE',
    name: 'AI Chatbot Disclosure',
    description: 'Verify disclosure when interacting with AI systems',
    regulation: 'AI_ACT',
    articles: ['Art.52'],
    category: 'AI_OVERSIGHT',
    severity: 'MEDIUM',
    automatable: true,
    query: {
      requiredNodes: [
        { alias: 'disclosure', type: 'EVENT', filters: { event_type: 'AI.TRANSPARENCY.DISCLOSED', 'payload.disclosureType': 'CHATBOT' }, optional: true },
      ],
      requiredEdges: [],
    },
    proofCriteria: [
      {
        id: 'chatbot-disclosure',
        description: 'Chatbot AI disclosure exists',
        type: 'EXISTS',
        params: { nodeAlias: 'disclosure' },
        weight: 100,
        mandatory: false,
      },
    ],
  },
];

// ═══════════════════════════════════════════════════════════════
// ALL QUERIES COMBINED
// ═══════════════════════════════════════════════════════════════

export const ALL_COMPLIANCE_QUERIES: ComplianceQuery[] = [
  ...GDPR_QUERIES,
  ...DORA_QUERIES,
  ...NIS2_QUERIES,
  ...AI_ACT_QUERIES,
];

// Query lookup by ID
export const QUERY_BY_ID: Record<string, ComplianceQuery> = ALL_COMPLIANCE_QUERIES.reduce(
  (acc, query) => ({ ...acc, [query.queryId]: query }),
  {}
);

// Queries by regulation
export const QUERIES_BY_REGULATION: Record<string, ComplianceQuery[]> = {
  GDPR: GDPR_QUERIES,
  DORA: DORA_QUERIES,
  NIS2: NIS2_QUERIES,
  AI_ACT: AI_ACT_QUERIES,
};
